### ISSUE TITLE
Main page Flex layout

### ISSUE THREAD

**Issue by BrijeshBumrela** [hardlyhuman/tfexplorer-ui#3]
Implement the CSS flex layout as described below for the main page of our app

refer `src/container/main.js`
start writing the HTML code inside
`return (  
            <div className={classes.heading}>Main Page</div>
 );` 

& CSS inside main.module.css

![flex](https://user-images.githubusercontent.com/37417813/81319831-e3929d80-90ad-11ea-8908-ffabc3279814.png)

**Comment by siddharth25pandey** [comment]
Assign this issue to me. Thanks!
