### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by BrijeshBumrela** [hardlyhuman/tfexplorer-ui#6]
Add more details to the readme. write how to run the app using package.json scripts. Reference tfexplorer backend repo (& link)

[https://github.com/hardlyhuman/TFExplorer/issues/3](https://github.com/hardlyhuman/TFExplorer/issues/3)

**Comment by siddharth25pandey** [comment]
Assign this issue to me.

**Comment by siddharth25pandey** [comment]
Also tell me what are the details we have to write in it.
